<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-11-02 17:06
=======
# Generated by Django 3.2.8 on 2021-11-02 14:21
>>>>>>> eb9dadfa825f474b5d127d12822823d1dc794dad

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
