# Generated by Django 3.2.8 on 2021-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notionboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Hit',
        ),
    ]
